apiVersion: v1
kind: Service
metadata:
  name: data-tool
  namespace: fitnessapp
spec:
  selector:
    app: data-tool
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
