apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  namespace: fitnessapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: fitnessaiapp-ai:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: fitnessapp-config
            - secretRef:
                name: fitnessapp-secret
          readinessProbe:
            httpGet:
              path: /docs
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
